import java.util.Scanner;
import java.util.Random;

public class NumberGame {
    public static void main(String[] args) {
        Random r = new Random();
        Scanner sc = new Scanner(System.in);
        int score = 0;
        System.out.println("\nGUESS THE RANDOM NUMBER GENERATED BY THE SYSTEM (BETWEEN 1 - 100).");
        System.out.println("YOU HAVE 5 GUESSES.");
        System.out.println("\nEnter the number of rounds you want to play:");
        int rounds = sc.nextInt();
        for (int i = 0; i < rounds; i++) {

            int RandomNumber = r.nextInt(100);
            int count = 0;
            System.out.println("\nRound: " + (i + 1));

            while (count <= 4) {
                System.out.println("Your guess:");
                int Guess = sc.nextInt();

                if (Guess == RandomNumber) {
                    System.out.println("Congratulations You Guessed the correct number.");
                    score = score + 100;
                    break;
                } else if (Guess > RandomNumber) {
                    System.out.println("Your guess is High. Try Lower! (" + (count + 1) + " Guess Done).");
                    count++;
                } else if (Guess < RandomNumber) {
                    System.out.println("Your guess is Low. Try Higher! (" + (count + 1) + " Guess Done).");
                    count++;
                }
            }
            System.out.println("\nYOUR SCORE = " + score);
            System.out.println("Correct Number Was: " + RandomNumber);
            if (count == 5) {
                System.out.println("\nSORRY! YOU DID'NT GUESS THE CORRECT NUMBER IN 5 GUESSES.");
            }
        }
        sc.close();
    }

}